In [5]:
# Temperatura: Medidas 0, 10, 20, 30, 40   (10 medidas de cada) 
# Amp.: Medidas        5, 10, 15, 18, 20
# Distribución de las medidas siguen una normal
from numpy import random
import numpy as np
medida0=random.normal(loc=5  ,scale=0.5,size=10)
medida10=random.normal(loc=10,scale=0.5,size=10)
medida20=random.normal(loc=15,scale=0.5,size=10)
medida30=random.normal(loc=18,scale=0.5,size=10)
medida40=random.normal(loc=20,scale=0.5,size=10)
medida40
np.concatenate((medida0,medida10,medida20,medida30,medida40)).reshape(5,10)

array([[ 4.66796281,  5.54583285,  4.95173315,  4.43897734,  5.28600988,
         3.78221369,  5.80039348,  4.62469181,  6.18804577,  5.01638406],
       [ 9.85134445,  9.45751895, 10.57861836,  9.99509065,  9.59191736,
         9.51132357,  9.37520351,  9.19055998,  9.99058367,  9.64230828],
       [14.84716312, 15.75647689, 15.58301152, 14.52422528, 14.88580866,
        14.91486669, 14.92710845, 15.11626682, 14.28066745, 15.36723558],
       [17.99001919, 18.4495204 , 18.34258686, 17.87343302, 18.55667002,
        18.17759435, 18.41184498, 17.55254617, 18.66081245, 19.02415971],
       [20.78642063, 21.14870652, 19.72453823, 19.76209582, 20.66825338,
        19.76977144, 19.84581057, 19.77203933, 19.69962361, 19.59843368]])

In [6]:
serie1=np.stack((medida0,medida10, medida20, medida30, medida40))
temperatura=np.arange(0,50,10)
temperaturas=np.stack((temperatura,)*10)
temperaturas=temperaturas.transpose()

In [7]:
series=np.empty((2,5,10))
series[0]=temperaturas
series[1]=serie1

In [8]:
series

array([[[ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [10.        , 10.        , 10.        , 10.        ,
         10.        , 10.        , 10.        , 10.        ,
         10.        , 10.        ],
        [20.        , 20.        , 20.        , 20.        ,
         20.        , 20.        , 20.        , 20.        ,
         20.        , 20.        ],
        [30.        , 30.        , 30.        , 30.        ,
         30.        , 30.        , 30.        , 30.        ,
         30.        , 30.        ],
        [40.        , 40.        , 40.        , 40.        ,
         40.        , 40.        , 40.        , 40.        ,
         40.        , 40.        ]],

       [[ 4.66796281,  5.54583285,  4.95173315,  4.43897734,
          5.28600988,  3.78221369,  5.80039348,  4.62469181,
          6.18804577,  5.01638406],
        [ 9.85134445,  9.45751895, 10.57861836,  9

In [9]:
import scipy.stats as st
st.describe(serie1)

DescribeResult(nobs=5, minmax=(array([4.66796281, 5.54583285, 4.95173315, 4.43897734, 5.28600988,
       3.78221369, 5.80039348, 4.62469181, 6.18804577, 5.01638406]), array([20.78642063, 21.14870652, 19.72453823, 19.76209582, 20.66825338,
       19.76977144, 19.84581057, 19.77203933, 19.69962361, 19.59843368])), mean=array([13.62858204, 14.07161112, 13.83609762, 13.31876442, 13.79773186,
       13.23115395, 13.6720722 , 13.25122082, 13.76394659, 13.72970426]), variance=array([41.57548695, 41.51722082, 36.89424735, 38.40302187, 40.29343906,
       43.29382251, 35.64550348, 38.8517099 , 32.77777459, 39.44587676]), skewness=array([-0.33558911, -0.28713859, -0.5423095 , -0.43825813, -0.2815974 ,
       -0.48053975, -0.29330045, -0.39886314, -0.2410686 , -0.42295451]), kurtosis=array([-1.25726823, -1.4370526 , -1.17097382, -1.19984365, -1.4015948 ,
       -1.23316334, -1.48982179, -1.34952492, -1.45457129, -1.38878343]))

In [10]:
st.describe(serie1, axis=1).mean

array([ 5.03022448,  9.71844688, 15.02028305, 18.30391872, 20.07756932])

In [22]:
import statsmodels.formula.api as smf

X=series[1].flatten() 
Y=series[0].flatten()
model = smf.ols(formula='Y~X+1',data={'Y':Y,'X':X}).fit()
print_model = model.summary()
print(print_model)


                            OLS Regression Results                            
Dep. Variable:                      Y   R-squared:                       0.980
Model:                            OLS   Adj. R-squared:                  0.979
Method:                 Least Squares   F-statistic:                     1124.
Date:                Thu, 22 Oct 2020   Prob (F-statistic):           2.08e-40
Time:                        10:48:36   Log-Likelihood:                -106.20
No. Observations:                  50   AIC:                             218.4
Df Residuals:                      47   BIC:                             224.1
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -3.1185      1.786     -1.