# Introducción a NUMPY

In [1]:
import numpy as np
print('Bienvenido a NUMPY !!!')

Bienvenido a NUMPY !!!


In [2]:
matriz = np.array( [1,2,3,4,5] )
matriz

array([1, 2, 3, 4, 5])

In [3]:
print(matriz)

[1 2 3 4 5]


In [4]:
matriz2D = np.array([[1,2,3],[4,5,6]])
print(matriz2D)

[[1 2 3]
 [4 5 6]]


In [8]:
matriz3D = np.array( [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]  )
print(matriz3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Para saber el numero de dimensiones de mi matriz, puedo utilizar el atributo ndim del objeto array de numpy:

In [9]:
matriz3D.ndim

3

Para saber e tamaño de la matriz, puedo utilizar el atributo shape

In [10]:
matriz3D.shape

(2, 2, 3)

Para sabe cúanto ocupa en RAM cada item del array, puedo utilizar el atributo itemsize

In [ ]:
matriz3D.itemsize

In [12]:
matriz2D.itemsize

8

El tamaño por defecto de lo ocupa cada dato, depende del Sistema Operativo, y de la impletanción de la librería C que haya por debajo de numpy.
En mi caso, el tipo de dato es un int64-> 8 bytes-> 64 bits

**El tipo de dato lo fuerzo al pasar el atributo dtype cuando creamos la matriz**

In [13]:
matriz3D = np.array( [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] , 
                    dtype=np.int8 )
print(matriz3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
matriz3D.itemsize

1

En este caso, ya ocupa 1 byte, es decir 8 bits

# Otras formas de crear arrays

In [15]:
matriz_vacia = np.empty([2,2], dtype=np.float32)
print(matriz_vacia)

[[ 1.2845056e+07 -7.5929548e-38]
 [ 2.2813139e-41  2.5243549e-29]]


En este caso, lo que pasamos son los tamaños en cada dimensión, y los valores iniciales de la matriz no se preasignan... puede contener CUALQUIER COSA

In [16]:
matriz_ceros = np.zeros([2,2], dtype=np.float32)
print(matriz_ceros)

[[0. 0.]
 [0. 0.]]


In [17]:
matriz_unos = np.ones([2,2], dtype=np.float32)
print(matriz_unos)

[[1. 1.]
 [1. 1.]]


Crear matrices con RANGOS DE NUMEROS

In [18]:
matriz_rangos = np.arange(5)
matriz_rangos

array([0, 1, 2, 3, 4])

In [19]:
matriz_rangos = np.arange(5,10)
matriz_rangos

array([5, 6, 7, 8, 9])

In [20]:
matriz_rangos = np.arange(5,10,2) # El 2 es el paso, el incremento
matriz_rangos

array([5, 7, 9])

In [28]:
matriz_rangos = np.arange(5,11,2, endpoint=True) 
matriz_rangos

TypeError: 'endpoint' is an invalid keyword argument for arange()

In [23]:
matriz_rangos = np.arange(5,10,2.5) 
matriz_rangos

array([5. , 7.5])

En ocasiones esto de arriba puede dar un resultado que no sea el que esperemos.... Debido a las operaciones con coma flotante

In [26]:
matriz_rangos = np.arange(0,10,1/6) 
matriz_rangos

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ,
       1.66666667, 1.83333333, 2.        , 2.16666667, 2.33333333,
       2.5       , 2.66666667, 2.83333333, 3.        , 3.16666667,
       3.33333333, 3.5       , 3.66666667, 3.83333333, 4.        ,
       4.16666667, 4.33333333, 4.5       , 4.66666667, 4.83333333,
       5.        , 5.16666667, 5.33333333, 5.5       , 5.66666667,
       5.83333333, 6.        , 6.16666667, 6.33333333, 6.5       ,
       6.66666667, 6.83333333, 7.        , 7.16666667, 7.33333333,
       7.5       , 7.66666667, 7.83333333, 8.        , 8.16666667,
       8.33333333, 8.5       , 8.66666667, 8.83333333, 9.        ,
       9.16666667, 9.33333333, 9.5       , 9.66666667, 9.83333333])

In [27]:
matriz_por_trozos = np.linspace(0,10,10)
matriz_por_trozos

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

# Extracción de datos de una matriz

In [32]:
matriz=np.array([3,2,5,8,6,3,8,9,2,6])
matriz

array([3, 2, 5, 8, 6, 3, 8, 9, 2, 6])

In [33]:
matriz[5] # Extraemos el elemento en la posición 6, 
            #o la 5 si contamos desde el 0, que es como cuenta python

3

In [35]:
matriz[-3] # En esta caso cuanta desde atrás, contando desde -1

9

In [36]:
matriz[2:5] # Esto obtiene un rango... el último no se incluye

array([5, 8, 6])

In [37]:
matriz[2:] # Desde el segundo (tercero) hasta el final

array([5, 8, 6, 3, 8, 9, 2, 6])

In [38]:
matriz[:5] # Desde el principio hasta el quinto

array([3, 2, 5, 8, 6])

In [39]:
matriz[2:8:3] # Desde 2 al 8, pero de 3 en 3
#5, 3

array([5, 3])

In [45]:
matriz2D = np.array( [ [1,2,3], [4,5,6], [7,8,9]] )
matriz2D


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
matriz2D.ndim


2

In [42]:
matriz2D.shape

(3, 3)

In [43]:
matriz2D[1,2]

6

In [44]:
matriz2D[2,1]

8

In [48]:
matriz2D[1:,1:]

array([[5, 6],
       [8, 9]])

In [49]:





matriz2D = np.array( [ [1,2,3], [4,5,6], [7,8,9]] )
matriz2D


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
matriz2D[1,0]

4

In [54]:
matriz2D[1,0:2]

array([4, 5])

In [55]:
#matriz2D[filas, columas]
matriz2D[1:3,1]

array([5, 8])

In [56]:
# Quiero la fila 4, 5 y 6
matriz2D[1,...]

array([4, 5, 6])

In [57]:
matriz2D[...,1]

array([2, 5, 8])

In [58]:
matriz2D[:,1]

array([2, 5, 8])

In [59]:
matriz2D[matriz2D>5]

array([6, 7, 8, 9])

In [63]:
11/4  # División completa

2.75

In [64]:
11//4 # División entera

2

In [65]:
11%4  # Resto de la división entera

3

In [66]:
matriz2D[matriz2D%2==0]

array([2, 4, 6, 8])

In [67]:
matriz2D%2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [68]:
matriz2D*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [69]:
matriz2D+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [70]:
matriz2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
matriz2D.shape

(3, 3)

In [73]:
matriz2D[...,2].shape

(3,)

In [74]:
987

987

# Operaciones binarias ( filtros )

In [75]:
matriz=np.array([[1,2,3],[4,5,6]])
print(matriz)

[[1 2 3]
 [4 5 6]]


In [76]:
filtro=np.array([[True,False,False],[True,True,False]])
print(filtro)

[[ True False False]
 [ True  True False]]


In [77]:
matriz[filtro]

array([1, 4, 5])

In [80]:
filtro=np.array([[1,0,0],[1,1,0]])
print(filtro)

[[1 0 0]
 [1 1 0]]


In [83]:
matriz[filtro==1]

array([1, 4, 5])

In [84]:
matriz%2

array([[1, 0, 1],
       [0, 1, 0]])

In [97]:
matriz%2==0,1

(array([[False,  True, False],
        [ True, False,  True]]),
 1)

In [87]:
matriz=np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
divisibles_entre_tres=matriz%3==0

In [101]:
divisibles_entre_tres_resto_uno=matriz%3==1

In [103]:
np.bitwise_or(divisibles_entre_tres,divisibles_entre_tres_resto_uno)

array([[ True, False,  True],
       [ True, False,  True]])

In [106]:
# Operador: +, - /, * -> Trabajan sobre 2 elementos -> Los teneis en numpy
# Operador: logicos NO ESTAN EN NUMPY ->> EXISTEN FUNCIONES EQUIVALENTES
    # and, or, not
    # bitwise_and, bitwise_or, invert
3==6
3!=6
#nombre(argumentos)

True

In [111]:
divisibles_entre_tres

array([[False, False,  True],
       [False, False,  True]])

In [112]:
np.invert(divisibles_entre_tres)

array([[ True,  True, False],
       [ True,  True, False]])

In [114]:
np.bitwise_or(divisibles_entre_tres_resto_uno , divisibles_entre_tres)

array([[ True, False,  True],
       [ True, False,  True]])

In [115]:
matriz[np.bitwise_or(divisibles_entre_tres_resto_uno , 
                     divisibles_entre_tres)]

array([1, 3, 4, 6])

In [116]:
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
matriz>3

array([[False, False, False],
       [ True,  True,  True]])

In [119]:
mayores_que_tres=matriz[matriz>3]

In [120]:
mayores_que_tres[mayores_que_tres%5==0]

array([5])

In [122]:
matriz=np.array([[1,2,3,4,5],[6,7,8,9,10]])
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [123]:
# Los elemento menores que 4 o mayores que 7
matriz<4

array([[ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [124]:
matriz>7

array([[False, False, False, False, False],
       [False, False,  True,  True,  True]])

In [125]:
np.bitwise_or(matriz<4,matriz>7)

array([[ True,  True,  True, False, False],
       [False, False,  True,  True,  True]])

In [126]:
matriz[np.bitwise_or(matriz<4,matriz>7)]

array([ 1,  2,  3,  8,  9, 10])

# Iterar sobre el array

In [127]:
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [128]:
for x in matriz:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [134]:
for fila in matriz:
    for valor in fila:
        print('Estoy procesando el valor: '+str(valor*2))
        
# matriz_doblada
# print(matriz_doblada)

Estoy procesando el valor: 2
Estoy procesando el valor: 4
Estoy procesando el valor: 6
Estoy procesando el valor: 8
Estoy procesando el valor: 10
Estoy procesando el valor: 12
Estoy procesando el valor: 14
Estoy procesando el valor: 16
Estoy procesando el valor: 18
Estoy procesando el valor: 20


In [135]:
matriz*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [136]:
matriz=np.array([1,2,3])
print(matriz)

[1 2 3]


In [137]:
matriz[1]=5
print(matriz)

[1 5 3]


In [140]:
matriz=np.array([[1,2],[3,4],[5,6]])
print(matriz)


[[1 2]
 [3 4]
 [5 6]]


In [141]:
for fila in matriz:
    print(fila)

[1 2]
[3 4]
[5 6]


In [142]:
matriz.shape

(3, 2)

In [143]:
matriz.shape[0]

3

In [144]:
range(0,matriz.shape[0])

range(0, 3)

In [145]:
## Navegar entre los numero de fila de la matriz
for numero_fila in range(0,matriz.shape[0]):
    print(numero_fila)

0
1
2


In [146]:
## Navegar entre los numero de columna de la matriz
for numero_columna in range(0,matriz.shape[1]):
    print(numero_columna)

0
1


In [147]:
for numero_fila in range(0,matriz.shape[0]):
    for numero_columna in range(0,matriz.shape[1]):
        matriz[numero_fila,numero_columna]=matriz[numero_fila,numero_columna]*2

In [148]:
matriz

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [157]:
matriz=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [155]:
matriz_transpuesta=np.array([[1,4,7],[2,5,8],[3,6,9]])
matriz_transpuesta

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [163]:
tamano_original=matriz.shape
filas=tamano_original[0]
columnas=tamano_original[1]
nuevo_tamano=(filas,columnas)
matriz_transpuesta=np.empty(nuevo_tamano, dtype=matriz.dtype)

for numero_fila in range(0,matriz.shape[0]):
    for numero_columna in range(0,matriz.shape[1]):
        matriz_transpuesta[numero_fila,numero_columna]=matriz[numero_columna,numero_fila]

matriz_transpuesta        

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [161]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [162]:
matriz.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [164]:
datos=np.array([1.4, 1.5, 1.2, 1.7, 1.9, 1.4, 1.2])
datos

array([1.4, 1.5, 1.2, 1.7, 1.9, 1.4, 1.2])

In [165]:
np.mean(datos)

1.4714285714285713

In [166]:
np.median(datos)

1.4

In [173]:
np.std(datos)
np.var(datos)

0.05632653061224489

In [ ]:
# Desviación típica: Regla Chevichev
# En un intervalo de 1 desv. tip arriba y abajo de la 
# media la menos tengo el 50% de los datos
# LA MAYOR PARTE DE LOS DATOS ESTA EN EL INTERVALO 1 std +- media

# RANGO INTERCUARTILICO : Q3-Q1 = P75-P25


In [169]:
np.percentile(datos,75)-np.percentile(datos,25)

0.30000000000000027

In [170]:
(np.percentile(datos,75)-np.percentile(datos,25))/2

0.15000000000000013

In [171]:
np.amax(datos)

1.9

In [172]:
np.amin(datos)

1.2

In [178]:
# Quiero los datos más centrados: Q1-Q3 -> 50%
Q3=np.percentile(datos,75)
filtro_menores_Q3=datos<Q3

Q1=np.percentile(datos,25)
filtro_mayores_Q1=datos>Q1

datos[np.bitwise_and(filtro_mayores_Q1,filtro_menores_Q3)]

array([1.4, 1.5, 1.4])

In [179]:
datos[np.bitwise_and( datos< np.percentile(datos,75) , datos> np.percentile(datos,25)  )]

array([1.4, 1.5, 1.4])

# Reshapes

In [180]:
matriz=np.arange(12)
matriz

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [181]:
matriz.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [185]:
matriz.reshape(2,2,3).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [186]:
matrizA=np.arange(6)
matrizB=np.arange(6,12)


In [187]:
matrizA

array([0, 1, 2, 3, 4, 5])

In [188]:
matrizB

array([ 6,  7,  8,  9, 10, 11])

In [189]:
matrizA+matrizB

array([ 6,  8, 10, 12, 14, 16])

In [190]:
matrizA-matrizB


array([-6, -6, -6, -6, -6, -6])

In [191]:
matrizA*matrizB

array([ 0,  7, 16, 27, 40, 55])

In [192]:
matrizA@matrizB

145

In [197]:
np.dot(matrizA,matrizB)

145

In [198]:
np.matmul(matrizA,matrizB)

145

In [199]:
np.vdot(matrizA,matrizB)

145

In [205]:
matriz=np.array([[1,2],[3,4]])
np.linalg.det(matriz)

-2.0000000000000004

In [206]:
np.inner(matrizA,matrizB)

145

In [207]:
matrizA

array([0, 1, 2, 3, 4, 5])

In [208]:
matrizB

array([ 6,  7,  8,  9, 10, 11])

In [211]:
np.concatenate((matrizA,matrizB))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [213]:
np.stack((matrizA,matrizB))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])